-- ========================================
-- Jess Monnier
-- CSD-430 CRUD Project
-- Updated 21 September 2025
-- Database: csd430
-- User: student1
-- Tables: jess_bookstore_books, jess_bookstore_genres
-- ========================================

-- Ensure the database exists and is selected
CREATE DATABASE IF NOT EXISTS csd430;
USE csd430;

-- Create/reuse user and grant permissions
CREATE USER IF NOT EXISTS 'student1'@'localhost' IDENTIFIED BY 'pass';
GRANT ALL PRIVILEGES ON csd430.* TO 'student1'@'localhost';

-- Drop old tables if they exist
DROP TABLE IF EXISTS jess_bookstore_books;
DROP TABLE IF EXISTS jess_bookstore_genres;

-- Create genres table
CREATE TABLE jess_bookstore_genres (
    name VARCHAR(100) PRIMARY KEY
);

-- Create books table
CREATE TABLE jess_bookstore_books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    description TEXT,
    primary_genre VARCHAR(100),
    sub_genre VARCHAR(100),
    stock INT DEFAULT 0,
    cost DECIMAL(10,2) DEFAULT 0.00,
    FOREIGN KEY (primary_genre) REFERENCES jess_bookstore_genres(name) ON UPDATE CASCADE,
    FOREIGN KEY (sub_genre) REFERENCES jess_bookstore_genres(name) ON UPDATE CASCADE
);

-- Insert genres
INSERT INTO jess_bookstore_genres (name) VALUES 
("Science Fiction"), ("Fantasy"), ("Horror"), ("Romance"), 
("Literary Fiction"), ("Thriller"), ("Mystery"), ("Adventure"), 
("Young Adult"), ("Children's Fiction"), ("Historical Fiction"), 
("Biography/Memoir"), ("True Crime"), ("Self-Help"), ("History"), 
("Travel"), ("Philosophy"), ("Politics"), ("Cooking/Food"), 
("Psychology"), ("Science"), ("Business & Economics"), ("Religion"), 
("Health & Wellness"), ("Graphic Novel"), ("Poetry");

-- Insert books (book data generated by ChatGPT)
INSERT INTO jess_bookstore_books 
(title, author, description, primary_genre, sub_genre, stock, cost) VALUES

-- Fiction classics
("Pride and Prejudice", "Austen, Jane", 
 "A classic novel about manners, marriage, and social standing.", 
 "Literary Fiction", "Romance", 10, 9.99),

("1984", "Orwell, George", 
 "Dystopian novel about totalitarianism and surveillance.", 
 "Science Fiction", "Thriller", 12, 10.99),

("To Kill a Mockingbird", "Lee, Harper", 
 "A novel dealing with racial injustice in the American South.", 
 "Literary Fiction", "Historical Fiction", 9, 11.50),

("Moby-Dick", "Melville, Herman", 
 "Epic tale of a captain's obsession with a white whale.", 
 "Adventure", "Literary Fiction", 7, 12.00),

("Frankenstein", "Shelley, Mary", 
 "Gothic novel about a scientist who creates life.", 
 "Horror", "Science Fiction", 8, 10.50),

("The Great Gatsby", "Fitzgerald, F. Scott", 
 "Story of the American Dream and disillusionment.", 
 "Literary Fiction", "Romance", 10, 9.50),

-- Nonfiction
("The Diary of a Young Girl", "Frank, Anne", 
 "Writings from a Jewish girl hiding during WWII.", 
 "Biography/Memoir", "History", 6, 12.99),

("A Brief History of Time", "Hawking, Stephen", 
 "An accessible introduction to cosmology and physics.", 
 "Science", "Philosophy", 7, 15.00),

("The Art of War", "Tzu, Sun", 
 "Ancient treatise on military strategy and tactics.", 
 "Philosophy", "History", 10, 8.99),

("Thinking, Fast and Slow", "Kahneman, Daniel", 
 "Explores how humans think and make decisions.", 
 "Psychology", "Self-Help", 8, 13.99),

("The Power of Habit", "Duhigg, Charles", 
 "Examines the science of habit formation and change.", 
 "Self-Help", "Psychology", 9, 14.95),

("Steve Jobs", "Isaacson, Walter", 
 "Biography of Apple co-founder and innovator.", 
 "Biography/Memoir", "Business & Economics", 5, 17.50),

-- Fiction / Popular
("The Hobbit", "Tolkien, J.R.R.", 
 "Fantasy adventure of Bilbo Baggins in Middle-earth.", 
 "Fantasy", "Adventure", 8, 12.99),

("Gideon the Ninth", "Muir, Tamsyn", 
 "A blend of science fiction, fantasy, and gothic mystery featuring necromancers and deadly puzzles.", 
 "Science Fiction", "Fantasy", 6, 14.50),

("The Catcher in the Rye", "Salinger, J.D.", 
 "Story of teenage alienation and rebellion.", 
 "Literary Fiction", "Young Adult", 10, 9.99),

("The Girl with the Dragon Tattoo", "Larsson, Stieg", 
 "Mystery thriller involving a journalist and hacker.", 
 "Mystery", "Thriller", 6, 11.95),

("Gone Girl", "Flynn, Gillian", 
 "Psychological thriller about a missing wife.", 
 "Thriller", "Mystery", 7, 12.25),

("The Hunger Games", "Collins, Suzanne", 
 "Dystopian novel about survival and rebellion.", 
 "Science Fiction", "Young Adult", 9, 10.99),

("Anne of Green Gables", "Montgomery, L.M.", 
 "Coming-of-age story of an imaginative orphan girl.", 
 "Children's Fiction", "Literary Fiction", 6, 8.99),

("The Shining", "King, Stephen", 
 "Horror novel about a haunted hotel and a man's descent into madness.", 
 "Horror", "Thriller", 7, 11.50),

-- Additional Genres
("In Cold Blood", "Capote, Truman", 
 "A pioneering true crime novel about a brutal family murder.", 
 "True Crime", "Literary Fiction", 5, 12.00),

("How to Win Friends and Influence People", "Carnegie, Dale", 
 "Classic advice on interpersonal skills and leadership.", 
 "Self-Help", "Business & Economics", 10, 10.75),

("On the Road", "Kerouac, Jack", 
 "A novel about cross-country road trips and self-discovery.", 
 "Travel", "Literary Fiction", 7, 11.95),

("The Communist Manifesto", "Marx, Karl and Engels, Friedrich", 
 "Foundational political text advocating communism.", 
 "Politics", "Philosophy", 9, 8.25),

("Salt, Fat, Acid, Heat", "Nosrat, Samin", 
 "A guide to mastering the elements of good cooking.", 
 "Cooking/Food", "Health & Wellness", 5, 18.00),

("The Bible", "Various Authors", 
 "Sacred scriptures central to Christianity.", 
 "Religion", NULL, 12, 15.00),

("Why We Sleep", "Walker, Matthew", 
 "Exploring the vital importance of sleep for health.", 
 "Health & Wellness", "Science", 6, 13.50),

("Maus", "Spiegelman, Art", 
 "A graphic novel about the Holocaust using animal allegories.", 
 "Graphic Novel", "Biography/Memoir", 4, 14.25),

("Leaves of Grass", "Whitman, Walt", 
 "A landmark collection of American poetry.", 
 "Poetry", "Literary Fiction", 6, 9.75),

("The Book Thief", "Zusak, Markus", 
 "A story set in Nazi Germany narrated by Death.", 
 "Historical Fiction", "Young Adult", 7, 13.49),

("The Hound of the Baskervilles", "Doyle, Arthur Conan", 
 "Sherlock Holmes investigates a supernatural hound.", 
 "Mystery", "Adventure", 5, 10.25),

("Treasure Island", "Stevenson, Robert Louis", 
 "Classic pirate adventure novel.", 
 "Adventure", "Children's Fiction", 8, 9.25);